#!/usr/bin/env bash
#Bash script that installs nginx on web server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
