#!/usr/bin/env bash
#Bash script that installs nginx on web server

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.htm
sudo service nginx restart
