#!/usr/bin/env bash
#Bash script to Configure your Nginx server
#so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root   /usr/share/nginx/html;
	index  index.html index.htm;

	location /redirect_me {
		return 301 http://youtube.com/;
	}
}" > /etc/nginx/sites-available/default
sudo service nginx restart
