#!/usr/bin/env bash
#Bash script to Configure your Nginx server
#so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod -R 755 /var/www
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
redirected="\\\trewrite ^redirect_me https://www.youtube.com permanent;"
sudo sed -i "42i $redirected" /etc/nginx/sites-available/default
sudo service nginx restart
