#!/usr/bin/env bash
#Bash script to Configure your Nginx server
#so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo touch /var/www/html/notfound.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/notfound.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root   /var/www/html;
	index  index.html index.htm;

	location /redirect_me {
		return 301 http://youtube.com/;
	}

	error_page 404 /notfound.html;
	location = /custom_404.html {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default
sudo service nginx restart
