#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
##The name of the custom HTTP header must be X-Served-By
##The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo touch /usr/share/nginx/html/notfound.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/notfound.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
	root   /usr/share/nginx/html;
	index  index.html index.htm;
	location /redirect_me {
		return 301 http://youtube.com/;
	}
	error_page 404 /notfound.html;
	location = /notfound.html {
		root /usr/share/nginx/html;
		internal;
	}
	}
}" > /etc/nginx/sites-available/default
sudo service nginx restart