#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine to respect below requirements
#Configure HAproxy with version equal or greater than 1.5 so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#Make sure that HAproxy can be managed via an init script
#Make sure that your servers are configured with the right hostnames

sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfgbackup


printf %s "global
        log /dev/log    local0
        log /dev/log    local1 notice
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

listen holberton
        bind *:80
        mode http
        stats enable
        balance roundrobin
        option httpclose
        option forwardfor
        server 1450-web-01 34.75.254.10:80 check
        server 1450-web-02 34.75.125.125:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
