#!/usr/bin/env bash
#bash script Creates the file /var/run/holbertonscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#deletes the file and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
while true
do
	trap "echo I hate the kill command ; sudo rm /var/run/holbertonscript.pid" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	trap "sudo rm /var/run/holbertonscript.pid" SIGQUIT
	echo "To infinity and beyond"
	sleep 2
done
