#!/usr/bin/env bash
#bash script that displays content of /etc/passwd

FILENAME="/etc/passwd"
while IFS=: read -r username userid homedir
do
  echo "$username:$userid:$homedir" | cut -d ':' -f1,3,6
done < $FILENAME
