#!/usr/bin/env bash
#bash script to show clock till 12:59

export i=0
export j=1
while [ $i -le 12 ]
do
	echo "Hour: $i"
	while [ $j -lt 60 ]
	do
		echo "$j"
		j=$((j+1))
		if [ $j -ge 60 ]; then
			j=1
			break
		fi
	done
	i=$((i+1))
done
