#!/usr/bin/env bash
#Bash script to run Nginx as Nginx
wget -O run https://github.com/IhebChatti/holberton-system_engineering-devops/blob/master/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
chmod u+x run
./run
