#!/usr/bin/env bash
#Bash script to run Nginx as Nginx
pkill apache2
chmod 600 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
